name: BoM Flood Warning Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  post_warnings:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # ✅ Required for cache storage
      contents: read  # ✅ Required for repository access

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List available artifacts
        run: |
          echo "Checking available artifacts..."
          gh api repos/${{ github.repository }}/actions/artifacts | jq '.artifacts[] | {name: .name, created_at: .created_at}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore the latest posted warnings artifact
        continue-on-error: true  # ✅ Prevents failure if no artifact exists
        run: |
          ARTIFACT_ID=$(gh api repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[] | select(.name=="posted-warnings") | .id' | sort -n | tail -1)
          if [ -n "$ARTIFACT_ID" ]; then
            echo "Downloading artifact ID: $ARTIFACT_ID"
            gh api repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip > artifact.zip
            unzip -o artifact.zip
            rm artifact.zip
          else
            echo "No existing artifact found. Using empty posted_warnings.txt."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python flood_bot.py
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Debug - Check file contents after running bot
        run: cat ./posted_warnings.txt || echo "posted_warnings.txt is empty after execution"


      - name: Save updated posted warnings as an artifact
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: posted-warnings
          path: ./posted_warnings.txt
