name: BoM Flood Warning Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  post_warnings:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # ✅ Required for cache storage
      contents: read  # ✅ Required for repository access

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore posted warnings cache
        id: cache-posted-warnings
        uses: actions/cache@v4
        with:
          path: posted_warnings.txt
          key:  # ✅ Generates a new cache key per run
          restore-keys: |
            posted-warnings-cache-v1-  # ✅ Falls back to the latest available cache


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python flood_bot.py
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Debug - Check file contents after running bot
        run: cat ./posted_warnings.txt || echo "posted_warnings.txt is empty after execution"

      - name: Save updated posted warnings to cache
        if: always()  # ✅ Ensure cache updates even if the workflow fails
        uses: actions/cache@v4
        with:
          path: posted_warnings.txt
          key: posted-warnings-cache-v1-${{ github.run_number }}  # ✅ Store as a new cache version

      - name: Save updated posted warnings as an artifact
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: posted-warnings
          path: ./posted_warnings.txt
