name: BoM Flood Warning Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  post_warnings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure posted_warnings.txt exists before downloading
        run: |
          if [ ! -f posted_warnings.txt ]; then
            echo "Creating posted_warnings.txt..."
            touch posted_warnings.txt
          fi

      - name: Upload initial empty posted_warnings.txt if missing
        if: always()  # ✅ Always check for this condition
        uses: actions/upload-artifact@v4
        with:
          name: posted-warnings
          path: posted_warnings.txt

      - name: Restore previously posted warnings (ignore errors if missing)
        continue-on-error: true  # ✅ Ignore missing artifacts on first run
        uses: actions/download-artifact@v4
        with:
          name: posted-warnings
          path: .

      - name: Debug check if posted_warnings.txt exists
        run: ls -lah posted_warnings.txt || echo "posted_warnings.txt not found"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python flood_bot.py
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Save updated posted warnings
        uses: actions/upload-artifact@v4
        with:
          name: posted-warnings
          path: posted_warnings.txt
